# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.srcs/sources_1/bd/design_1/ip/design_1_convolve_0_0/design_1_convolve_0_0.xci
# IP: The module: 'design_1_convolve_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_request_fifo/mmap_request_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] -quiet

# IP: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_data_fifo/mmap_data_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] -quiet

# IP: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_request_fifo/mmap_request_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_request_fifo/mmap_request_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_data_fifo/mmap_data_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_data_fifo/mmap_data_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.srcs/sources_1/bd/design_1/ip/design_1_convolve_0_0/design_1_convolve_0_0.xci
# IP: The module: 'design_1_convolve_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_request_fifo/mmap_request_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] -quiet

# IP: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_data_fifo/mmap_data_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] -quiet

# IP: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_request_fifo/mmap_request_fifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_request_fifo/mmap_request_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_request_fifo || ORIG_REF_NAME==mmap_request_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_data_fifo/mmap_data_fifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/mmap_data_fifo/mmap_data_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmap_data_fifo || ORIG_REF_NAME==mmap_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/sekiro/Desktop/Shortcuts/Vivado/RC/Final/convolve_test/convolve_test.gen/sources_1/bd/design_1/ip/design_1_convolve_0_0/src/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
